---
swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Edge RESTful API reference
basePath: "/api/v1"
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
- name: custom-equipment
  description: Manages customized equipment tags

paths:
  "/mxc/custom/equipments":
    get:
      description: Get custom equipment list
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              "$ref": "#/definitions/CustomEquipment"
            example:
            - id: 1
              equipmentName: Promgram-1
              equipmentTags:
              - name: cpu
                dataType: float32
                access: ro
                size: 4
                description: all about cpu
              - name: mem
                dataType: float32
                access: ro
                size: 4
                description: all about memory
              - name: disk
                dataType: uint32
                access: ro
                size: 4
                description: all about disk
            - id: 2
              equipmentName: Promgram-2
              equipmentTags:
              - name: abc
                dataType: string
                access: ro
                size: 4
                description: description of abc
              - name: def
                dataType: string
                access: ro
                size: 4
                description: description of def
              - name: xyz
                dataType: string
                access: ro
                size: 4
                description: description of xyz
      tags:
      - custom-equipment
      security:
      - mx-api-token: []
    post:
      description: Create a new Custom Equipment with tags
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/CustomEquipment"
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/CustomEquipment"
            example:
              id: 1
              equipmentName: Promgram-1
              equipmentTags:
              - name: cpu
                dataType: float32
                access: ro
                size: 4
                description: all about cpu
              - name: mem
                dataType: float32
                access: ro
                size: 4
                description: all about memory
              - name: disk
                dataType: uint32
                access: ro
                size: 4
                description: all about disk
      tags:
      - custom-equipment
      security:
      - mx-api-token: []
    delete:
      description: Delete a Custom Equipment with assigned IDs
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: array
          items:
            type: integer
      responses:
        '200':
          description: success
      tags:
      - custom-equipment
      security:
      - mx-api-token: []
  "/mxc/custom/equipments/{id}":
    parameters:
    - name: id
      in: path
      type: integer
      required: true
    delete:
      description: Delete a Custom Equipment with assigned ID
      responses:
        '200':
          description: success
      tags:
      - custom-equipment
      security:
      - mx-api-token: []
    put:
      description: Update a Custom Equipment with assigned ID
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/CustomEquipment"
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/CustomEquipment"
            example:
              id: 1
              equipmentName: Promgram-1
              equipmentTags:
              - name: cpu
                dataType: float32
                access: ro
                size: 4
                description: all about cpu
              - name: mem
                dataType: float32
                access: ro
                size: 4
                description: all about memory
              - name: disk
                dataType: uint32
                access: ro
                size: 4
                description: all about disk
      tags:
      - custom-equipment
      security:
      - mx-api-token: []

definitions:
  CustomEquipment:
    title: Custom Equipment
    description: Custom Equipment object
    type: object
    required:
    - equipmentName
    - equipmentTags
    properties:
      id:
        type: integer
        description: ID of equipment
        readOnly: true
      equipmentName:
        description: Name of custom equipment
        type: string
      equipmentTags:
        description: Tag List of custom equipment
        type: array
        items:
          "$ref": "#/definitions/CustomEquipmentTag"
  CustomEquipmentTag:
    title: Tag
    description: Equipment's tag entry
    type: object
    required:
    - name
    - dataType
    - access
    - size
    - description
    properties:
      name:
        description: Name of tag
        type: string
        minLength: 1
        maxLength: 255
      dataType:
        description: Data type of tag
        type: string
        enum:
        - boolean
        - uint16
        - uint32
        - uint64
        - int16
        - int32
        - int64
        - float32
        - float64
        - string
        - bytearray
      access:
        description: Access type of tag
        type: string
        enum:
        - ro
        - wo
        - rw
      size:
        description: Size of tag in byte
        type: integer
      description:
        description: Description of tag
        type: string
        minLength: 0
        maxLength: 65535

