---
swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Edge RESTful API reference
basePath: "/api/v1"
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
- name: modbusslave
  description: Handles Modbus Slave configuration

paths:
  "/mxc/modbusslave":
    get:
      description: Get Modbus Slave Configuration
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/ModbusSlave"
            example:
              enable: true
              host: 0.0.0.0
              port: 502
              unitId: 255
              ignoreUnitId: false
              anyHost: true
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    put:
      description: Update Modbus Slave Configuration
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/ModbusSlave"
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/ModbusSlave"
            example:
              enable: true
              host: 0.0.0.0
              port: 502
              unitId: 255
              ignoreUnitId: false
              anyHost: true
      tags:
      - modbusslave
      security:
      - mx-api-token: []
  "/mxc/modbusslave/mappings":
    get:
      description: Get Modbus Slave Mapping Table
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              "$ref": "#/definitions/MappingEntry"
            example:
            - id: 1
              reference: '0x40000'
              quantity: 1
              equipmentName: My_ioLogik-E2242
              equipmentType: modbus
              tagName: ai0
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    post:
      description: Create a Mapping Entry
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/MappingEntry"
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/MappingEntry"
            example:
              id: 1
              reference: '0x40000'
              quantity: 1
              equipmentName: My_ioLogik-E2242
              equipmentType: modbus
              tagName: ai0
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    put:
      description: Update Modbus Slave Mapping Table
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: array
          items:
            "$ref": "#/definitions/MappingEntry"
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              "$ref": "#/definitions/MappingEntry"
            example:
            - id: 1
              reference: '0x40000'
              quantity: 1
              equipmentName: My_ioLogik-E2242
              equipmentType: modbus
              tagName: ai0
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    delete:
      description: Delete a list of MappingEntry with assigned ID
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: array
          items:
            type: integer
      responses:
        '200':
          description: success
      tags:
      - modbusslave
      security:
      - mx-api-token: []
  "/mxc/mxmodbusslave/mappings/{id}":
    parameters:
    - name: id
      in: path
      type: integer
      required: true
    get:
      description: Get a MappingEntry with assigned ID
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/MappingEntry"
            example:
              id: 1
              reference: '0x40000'
              quantity: 1
              equipmentName: My_ioLogik-E2242
              equipmentType: modbus
              tagName: ai0
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    delete:
      description: Delete a MappingEntry with assigned ID
      responses:
        '200':
          description: success
      tags:
      - modbusslave
      security:
      - mx-api-token: []
    put:
      description: Update a MappingEntry with assigned ID
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/MappingEntry"
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/MappingEntry"
            example:
              id: 1
              reference: '0x40000'
              quantity: 1
              equipmentName: My_ioLogik-E2242
              equipmentType: modbus
              tagName: ai0
      tags:
      - modbusslave
      security:
      - mx-api-token: []

definitions:
  ModbusSlave:
    title: ModbusSlave
    required:
    - enable
    - port
    properties:
      enable:
        type: boolean
        description: Enable/Disable ModbusSlave function
      host:
        type: string
        description: IP or Hostname of Modbus Slave
        pattern: "^[A-Za-z0-9._-]+$"
      port:
        type: integer
        description: Port number of Modbus Slave
      unitId:
        type: integer
        description: Modbus Device ID (default 0xFF for Modbus-TCP)
        pattern: "^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-3][0-9]|24[0-7]|255)$"
      ignoreUnitId:
        type: boolean
        description: Ignore Unit ID
      anyHost:
        type: boolean
        description: Bind Modbus Slave at any network interface
    example:
      enable: true
      host: 0.0.0.0
      port: 502
      unitId: 255
      ignoreUnitId: false
      anyHost: true
  MappingEntry:
    title: MappingEntry
    required:
    - reference
    - quantity
    - equipmentName
    - equipmentType
    - tagName
    properties:
      id:
        type: integer
        description: Identity for MappingEntry
      reference:
        type: string
        description: Modbus access address (or offset)
        pattern: "^(0x[0134][0-9A-Fa-f]{4})$"
      quantity:
        type: integer
        description: Modbus access quantity
      equipmentName:
        type: string
        description: Equipment Name of Tag
        pattern: "^[A-Za-z0-9_-]+$"
        minLength: 3
        maxLength: 255
      equipmentType:
        type: string
        description: Type of Tag
      tagName:
        type: string
        description: Tag Name of Tag
        pattern: "[A-Za-z0-9_-]+"
        minLength: 2
        maxLength: 255
    example:
      id: 1
      reference: '0x40000'
      quantity: 1
      equipmentName: My_ioLogik-E2242
      equipmentType: modbus
      tagName: ai0
