swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: service
    description: Manages the system service configuration

paths:
  '/system/services':
    get:
      description: Get system services status
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              '$ref': '#/definitions/Service'
            example:
              - id: 1
                enable: true
                name: ssh
                status: true
              - id: 2
                enable: true
                name: rsyslog
                status: true
      tags:
        - service
      security:
        - mx-api-token: []
  '/system/services/{name}':
    put:
      description: Update service settings
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/Service'
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/Service'
            example:
              id: 1
              enable: true
              name: ssh
              status: true
      tags:
        - service
      security:
        - mx-api-token: []
    get:
      parameters:
        - name: name
          in: path
          required: true
          type: string
      description: Get specific service status
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/Service'
            example:
              id: 1
              enable: true
              name: ssh
              status: true
      tags:
        - service
      security:
        - mx-api-token: []

definitions:
  Service:
    description: Service status / configuration
    type: object
    required:
      - enable
    properties:
      id:
        description: Service ID
        type: integer
        readOnly: true
      enable:
        description: Enable/Disable service
        type: boolean
      name:
        description: Name of service
        type: string
        readOnly: true
      status:
        description: Current status of service
        type: string
        readOnly: true
    example:
      id: 1
      enable: true
      name: ssh
      status: true
