swagger: "2.0"

info:
  version: 4.1.0
  title: ThingsPro Gateway Cellular RESTful API reference
basePath: /api/v1
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: cellular
    description: Handles the Cellular interfaces

paths:
  /network/cellulars:
    get:
      summary: Cellular Interface(s)
      description: |
        The system returns information about the settings of all
        *Cellular interface(s)*.
      parameters: []
      responses:
        200:
          description: An array of Cellular interface(s)
          schema:
            type: array
            items:
              $ref: '#/definitions/CellularAll'
            example:
              - id: 1
                name: wwan1
                capabilities:
                  sim:
                  - 1
                  - 2
                  carriers:
                  - ATT
                  - SPRINT
                mode: lte
                signal:
                  rat: lte
                  csq: 14
                  rssi: -76
                  rxqual: 1
                  rscp: -80
                  ecio: -8.5
                  rsrp: -107.3
                  rsrq: -12.0
                  indicator: RSRP
                  level: 4
                operatorName: Chunghwa Telecom
                lac: "11114"
                tac: ""
                nid: ""
                cellId: "1249"
                bid: ""
                iccId: ""
                imsi: "466977502877452"
                imei: "356853050370859"
                esn: 802202F0
                pinRetryRemain: 3
                status: connected
                mac: 00:00:00:00:00:00
                ip: 111.70.146.125
                netmask: 255.255.255.252
                gateway: 111.70.146.126
                dns:
                - 168.95.1.1
                - 168.95.192.1
                usage:
                  txkbyte: 40023
                  rxkbyte: 3493
                currentProfileId: 1
                enable: true
                keepalive:
                  enable: true
                  targetHost: 8.8.8.8
                  intervalSec: 60
                  reboot:
                    enable: false
                    cycles: 1
                profileId: 1
                profileTimeout: 300
                profiles:
                - id: 1
                  pinCode: "0000"
                  pdpContext:
                    static: true
                    id: 1
                    apn: internet
                    type: ipv4v6
                    auth:
                      protocol: none
                      username: ""
                      password: ""
                  keepalive:
                    enable: false
                  init:
                  - sim:1
                  - carrier:ATT
      tags:
        - cellular
      security:
        - mx-api-token: []
  /network/cellulars/{id}:
    get:
      description: |
        Get settings of indicated Cellular interface.
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: An Cellular interface settings.
          schema:
            $ref: '#/definitions/CellularAll'
          examples:
            id: 1
            name: wwan1
            capabilities:
              sim:
              - 1
              - 2
              carriers:
              - ATT
              - SPRINT
            mode: umts
            signal:
              rat: lte
              csq: 14
              rssi: -76
              rxqual: 1
              rscp: -80
              ecio: -8.5
              rsrp: -107.3
              rsrq: -12.0
              indicator: RSRP
              level: 4
            operatorName: Chunghwa Telecom
            lac: "11114"
            tac: ""
            nid: ""
            cellId: "1249"
            bid: ""
            iccId: ""
            imsi: "466977502877452"
            imei: "356853050370859"
            esn: 802202F0
            pinRetryRemain: 3
            status: connected
            mac: 00:00:00:00:00:00
            ip: 111.70.146.125
            netmask: 255.255.255.252
            gateway: 111.70.146.126
            dns:
            - 168.95.1.1
            - 168.95.192.1
            usage:
              txkbyte: 40023
              rxkbyte: 3493
            currentProfileId: 1
            enable: true
            keepalive:
              enable: true
              targetHost: 8.8.8.8
              intervalSec: 60
              reboot:
                enable: false
                cycles: 1
            profileId: 1
            profileTimeout: 300
            profiles:
            - id: 1
              pinCode: "0000"
              pdpContext:
                static: true
                id: 1
                apn: internet
                type: ipv4v6
                auth:
                  protocol: none
                  username: ""
                  password: ""
              keepalive:
                enable: false
              init:
              - sim:1
              - carrier:ATT
      tags:
        - cellular
      security:
        - mx-api-token: []
    put:
      summary: Cellular Interface
      description: Update an Cellular interface settings.
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: ""
        required: true
        schema:
          $ref: '#/definitions/CellularSettings'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CellularSettings'
          examples:
            id: 1
            enable: true
            keepalive:
              enable: true
              targetHost: 8.8.8.8
              intervalSec: 60
              reboot:
                enable: false
                cycles: 1
            profileId: 1
            profileTimeout: 300
            profiles:
            - id: 1
              pinCode: "0000"
              pdpContext:
                static: true
                id: 1
                apn: internet
                type: ipv4v6
                auth:
                  protocol: none
                  username: ""
                  password: ""
              keepalive:
                enable: false
              init:
              - sim:1
              - carrier:ATT
            - id: 2
              pdpContext:
                id: 3
                static: false
                apn: ""
                type: ipv4
                auth:
                  protocol: none
                  username: ""
                  password: ""
              keepalive:
                targetHost: 1.2.3.4
              init:
              - carrier:VZW
      tags:
        - cellular
      security:
        - mx-api-token: []
  /network/cellulars/{id}/carrier:
    get:
      description: |
        Get carrier information of indicated Cellular interface.
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: carrier information of indicated Cellular interface.
          schema:
            $ref: '#/definitions/CellularCarrierInfo'
          examples:
            switchable: true
            current: ATT
            preferred: ATT
            available:
            - ATT
            - VZW
      tags:
        - cellular
      security:
        - mx-api-token: []
    put:
      description: Set preferred carrier
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: ""
        required: true
        schema:
          $ref: '#/definitions/CellularCarrierEntry'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CellularCarrierEntry'
          examples:
            carrier: VZW
      tags:
        - cellular
      security:
        - mx-api-token: []
  /network/cellulars/{id}/firmware:
    get:
      description: |
        Get firmware information of indicated Cellular interface.
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: firmware information of indicated Cellular interface.
          schema:
            $ref: '#/definitions/CellularFirmwareInfo'
          examples:
            switchable: true
            current:
              fwver: 05.05.58.01
              config: ATT_005.029_001
              carrier: ATT
            preferred:
              fwver: 05.05.58.01
              config: ATT_005.029_001
              carrier: ATT
            available:
            - fwver: 05.05.58.01
              config: ATT_005.029_001
              carrier: ATT
            - fwver: 05.05.58.02
              config: VZW_005.029_002
              carrier: VZW
      tags:
        - cellular
      security:
        - mx-api-token: []
    put:
      description: Set preferred firmware
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: ""
        required: true
        schema:
          $ref: '#/definitions/CellularFirmwareEntry'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CellularFirmwareEntry'
          examples:
            fwver: 05.05.58.01
            config: ATT_005.029_001
            carrier: ATT
      tags:
        - cellular
      security:
        - mx-api-token: []
definitions:
  CellularAll:
    title: Cellular Status & Settings
    allOf:
    - $ref: '#/definitions/CellularSettings'
    - $ref: '#/definitions/CellularStatus'
    example:
      id: 1
      name: wwan1
      capabilities:
        sim:
        - 1
        - 2
        carriers:
        - ATT
        - SPRINT
      mode: umts
      signal:
        rat: lte
        csq: 14
        rssi: -76
        rxqual: 1
        rscp: -80
        ecio: -8.5
        rsrp: -107.3
        rsrq: -12.0
        indicator: RSRP
        level: 4
      operatorName: Chunghwa Telecom
      lac: "11114"
      tac: ""
      nid: ""
      cellId: "1249"
      bid: ""
      iccId: ""
      imsi: "466977502877452"
      imei: "356853050370859"
      esn: 802202F0
      pinRetryRemain: 3
      status: connected
      mac: 00:00:00:00:00:00
      ip: 111.70.146.125
      netmask: 255.255.255.252
      gateway: 111.70.146.126
      dns:
      - 168.95.1.1
      - 168.95.192.1
      usage:
        txkbyte: 40023
        rxkbyte: 3493
      currentProfileId: 1
      enable: true
      keepalive:
        enable: true
        targetHost: 8.8.8.8
        intervalSec: 60
        reboot:
          enable: false
          cycles: 1
      profileId: 1
      profileTimeout: 300
      profiles:
      - id: 1
        pinCode: "0000"
        pdpContext:
          static: true
          id: 1
          apn: internet
          type: ipv4v6
          auth:
            protocol: none
            username: ""
            password: ""
        keepalive:
          enable: false
        init:
        - sim:1
        - carrier:ATT
  CellularCapabilities:
    properties:
      sim:
        type: array
        items:
          type: integer
      carriers:
        type: array
        items:
          type: string
    title: Cellular Capabilities
    example:
      sim:
      - 1
      - 2
      carriers:
      - ATT
      - SPRINT
  CellularStatus:
    type: object
    properties:
      name:
        type: string
        description: Interface name.
      capabilities:
        $ref: '#/definitions/CellularCapabilities'
      currentProfileId:
        type: integer
        description: Current used profile Id.
      mode:
        type: string
        description: |
          Given cellular connection mode. Could be one of `"umts"`, `"lte"`.
      signal:
        $ref: '#/definitions/CellularStatus_signal'
      operatorName:
        type: string
        description: Indicate current operator name if exist.
      lac:
        type: string
        description: Location area code.
      tac:
        type: string
        description: Tracking area code (LTE).
      nid:
        type: string
        description: Network ID (CDMA).
      cellId:
        type: string
        description: Cell ID.
      bid:
        type: string
        description: Base station ID (CDMA).
      iccId:
        type: string
        description: ICC ID of SIM card.
      imsi:
        type: string
        description: IMSI of SIM card.
      imei:
        type: string
        description: IMEI of cellular module.
      esn:
        type: string
        description: ESN of cellular module.
      pinRetryRemain:
        type: integer
        description: PIN Retry remaining.
      status:
        type: string
        description: |
          Indicate current status of cellular connection.

          - initializing: get module and SIM card info, unlock SIM card if
            necessary
          - nosim: no SIM card or unknown error with SIM card status

          - pin: SIM card is locked with a PIN code

          - ready: SIM card is ready for connect (unlocked or lock is
            disabled)
          - connecting: during connect state

          - connect_failure: connect failed or keepalive failed (if keepalive
            enabled)
          - connected: connect success with keepalive success or success with
            keepalive disabled
          - power_cycle: power cycle the module to recover issues

          - service_searching: roaming

          - service_attached: attached with a base station

          - pin_error: PIN code error

          - switching_carrier: module is switching carrier
        enum:
        - initializing
        - nosim
        - pin
        - puk
        - ready
        - connecting
        - connect_failure
        - connected
        - power_cycle
        - service_searching
        - service_attached
        - pin_error
        - switching_carrier
      mac:
        type: string
        description: The identical MAC address.
        readOnly: true
      ip:
        type: string
        description: IP address. `""` when not connected.
        pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3} (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
      netmask:
        type: string
        description: Subnet mask. `""` when not connected.
        pattern: |-
          ^(254|252|248|240|224|192|128)\.0\.0\.0|
            255\.(254|252|248|240|224|192|128|0)\.0\.0|
            255\.255\.(254|252|248|240|224|192|128|0)\.0|
            255\.255\.255\.(254|252|248|240|224|192|128|0)
      gateway:
        type: string
        description: Gateway IP address. `""` when not connected.
        pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3} (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
      dns:
        type: array
        description: A list of DNS IP addresses. `[]` when not connected.
        items:
          type: string
          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3} (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
      usage:
        $ref: '#/definitions/Usage'
    title: Cellular Status
  CellularSettings:
    properties:
      enable:
        type: boolean
        description: Enable Cellular Networking.
      id:
        type: integer
        description: Identifier for an Cellular interface.
      profileId:
        type: integer
        description: |
          Specify profile to connect, 0 for connect and retry automatically.
      profileTimeout:
        type: integer
        description: |
          Retry timeout in seconds for static APN to switch primary to
          secondary settings.
        minimum: 60
        maximum: 86399
      profiles:
        type: array
        description: Profiles for redundency
        items:
          $ref: '#/definitions/CellularProfile'
      keepalive:
        $ref: '#/definitions/Keepalive'
    title: Cellular Settings
    example:
      id: 1
      enable: true
      keepalive:
        enable: true
        targetHost: 8.8.8.8
        intervalSec: 60
        reboot:
          enable: false
          cycles: 1
      profileId: 1
      profileTimeout: 300
      profiles:
      - id: 1
        pinCode: "0000"
        pdpContext:
          static: true
          id: 1
          apn: internet
          type: ipv4v6
          auth:
            protocol: none
            username: ""
            password: ""
        keepalive:
          enable: false
        init:
        - sim:1
        - carrier:ATT
      - id: 2
        pdpContext:
          id: 3
          static: false
          apn: ""
          type: ipv4
          auth:
            protocol: none
            username: ""
            password: ""
        keepalive:
          targetHost: 1.2.3.4
        init:
        - carrier:VZW
  Usage:
    type: object
    required:
    - rxkbyte
    - txkbyte
    properties:
      txkbyte:
        type: integer
        description: Amount of data transmitted, in Kbytes.
      rxkbyte:
        type: integer
        description: Amount of data received, in Kbytes.
    title: Usage
    description: Data usage.
    example:
      txkbyte: 40023
      rxkbyte: 3493
  Keepalive:
    type: object
    properties:
      enable:
        type: boolean
        description: Enable/disable Cellular connection keep-alive by ping.
      targetHost:
        type: string
        description: IP address to ping.
      intervalSec:
        type: integer
        description: Check alive interval.
        minimum: 60
        maximum: 86399
      reboot:
        $ref: '#/definitions/KeepaliveReboot'
    title: Keepalive Settings
    example:
      enable: true
      targetHost: 8.8.8.8
      intervalSec: 60
      reboot:
        enable: false
        cycles: 1
  KeepaliveReboot:
    type: object
    properties:
      enable:
        type: boolean
        description: |
          Enable/disable reboot policy for check alive failed.
      cycles:
        type: integer
        description: |
          Define cycles to check if reboot is required; a cycle is
          a global value defined by system, default should be 20
          minutes.
        minimum: 1
        maximum: 48
    title: Reboot to Keepalive
    description: |
      Reboot system while check alive failed after a defined cycle(s).
    example:
      enable: true
      targetHost: 8.8.8.8
      intervalSec: 60
      reboot:
        enable: false
        cycles: 1
  CellularProfile:
    type: object
    required:
    - id
    - pdpContext
    properties:
      id:
        type: integer
        description: Identifier for an Cellular interface.
      name:
        type: string
        description: Alias name for the profile.
        minLength: 0
        maxLength: 100
      pdpContext:
        $ref: '#/definitions/CellularProfile_pdpContext'
      pinCode:
        type: string
        description: |
          PIN code of SIM card. Takes no effect when SIM card PIN
          weren't not set.
      init:
        type: array
        description: "Initialize process before executing the profile.\n\n- sim:\\\
          <sim-slot\\>\n\n- carrier:\\<carrier\\>    \n"
        items:
          type: string
    title: Cellular Profile
    example:
      id: 1
      pinCode: "0000"
      pdpContext:
        static: true
        id: 1
        apn: internet
        type: ipv4v6
        auth:
          protocol: none
          username: ""
          password: ""
      keepalive:
        enable: false
      init:
      - sim:1
      - carrier:ATT
  CellularCarrierInfo:
    type: object
    properties:
      switchable:
        type: boolean
        description: Cellular carrier could be switched or not.
        readOnly: true
      current:
        $ref: '#/definitions/CellularCarrierName'
      preferred:
        $ref: '#/definitions/CellularCarrierName'
      available:
        type: array
        items:
          $ref: '#/definitions/CellularCarrierName'
    title: CellularCarrierInfo
    description: |
      Display current, preferred, available carrier properties, if
      current carrier is not  equal to preferred carrier irmware, you should
      check your configuration. (fwver, config, carrier mismatch?).
    example:
      switchable: true
      current: ATT
      preferred: ATT
      available:
      - ATT
      - VZW
  CellularFirmwareInfo:
    type: object
    properties:
      switchable:
        type: boolean
        description: Cellular firmware could be switched or not.
        readOnly: true
      current:
        $ref: '#/definitions/CellularFirmwareEntry'
      preferred:
        $ref: '#/definitions/CellularFirmwareEntry'
      available:
        type: array
        items:
          $ref: '#/definitions/CellularFirmwareEntry'
    title: CellularFirmwareInfo
    description: |
      Display current, preferred, available firmware properties, if
      current firmware is not  equal to preferred firmware, you should
      check your configuration. (fwver, config, carrier mismatch?).
    example:
      switchable: true
      current:
        fwver: 05.05.58.01
        config: ATT_005.029_001
        carrier: ATT
      preferred:
        fwver: 05.05.58.01
        config: ATT_005.029_001
        carrier: ATT
      available:
      - fwver: 05.05.58.01
        config: ATT_005.029_001
        carrier: ATT
      - fwver: 05.05.58.02
        config: VZW_005.029_002
        carrier: VZW
  CellularCarrierName:
    type: string
    title: CellularCarrierName
    minLength: 0
    maxLength: 32
    description: Carrier name
  CellularCarrierEntry:
    type: object
    required:
    - carrier
    properties:
      carrier:
        type: string
        description: Carrier name
        minLength: 0
        maxLength: 32
    title: CellularCarrierEntry
    example:
      carrier: VZW
  CellularFirmwareEntry:
    type: object
    required:
    - carrier
    - config
    - fwver
    properties:
      fwver:
        type: string
        description: Firmware version
        minLength: 0
        maxLength: 32
      config:
        type: string
        description: Config name
        minLength: 0
        maxLength: 32
      carrier:
        type: string
        description: Carrier name
        minLength: 0
        maxLength: 32
    title: CellularFirmwareEntry
    description: ""
    example:
      fwver: 05.05.58.01
      config: ATT_005.029_001
      carrier: ATT
  CellularStatus_signal:
    required:
    - rat
    - csq
    - rssi
    - level
    - indicator
    properties:
      rat:
        type: string
        description: |
          Given cellular connection mode. Could be one of `umts`, `lte`, `m1`,
          `nb1`, `none`.
      csq:
        type: integer
        description: |
          Signal quality, Only shows the first part of the response, RSSI
          (Received signal strength indicator).
      rssi:
        type: integer
        description: |
          Cellular RF signal strength, in `dBm`. Value `-999` indicates no
          signal.
      rxqual:
        type: integer
        description: |
          RxQual is used in GSM and is a part of the Network Measurement Reports
          (NMR). This is an integer value which can be between 0 and 7 and
          reflects the quality of voice. 0 is the best quality, 7 is the worst.
      rscp:
        type: integer
        description: |
          In the UMTS cellular communication system, received signal code power
          (RSCP, in `dBm`) denotes the power measured by a receiver on a
          particular physical communication channel.
      ecio:
        type: integer
        description: |
          The ratio of the received energy per chip (= code bit) and the
          interference level, given in `dBm`.
      rsrp:
        type: integer
        description: |
          Reference Signal Received Power is an RSSI type of measurement. It is
          the power of the LTE Reference Signals spread over the full bandwidth
          and narrowband, given in `dBm`.
      rsrq:
        type: integer
        description: |
          Reference Signal Received Quality, Quality considering also RSSI and
          the number of used Resource Blocks (N) RSRQ = (N * RSRP) / RSSI
          measured over the same bandwidth. RSRQ is a C/I type of measurement
          and it indicates the quality of the received reference signal, given
          in `dB`.
      indicator:
        type: string
        description: |
          The indicator is either `RSSI` for 2G/3G or `RSRP` for 4G and `none`
          if no signal.
      level:
        type: integer
        description: |
          Signal levels defined in 6 degrees 0 ~ 5. The mapping is `no signal`,
          `very poor`, `poor`, `fair`, `good`, and `excellent`.
    description: Cellular RF signal strength, include RSSI and EcIo.
  CellularProfile_pdpContext_auth:
    required:
    - protocol
    properties:
      protocol:
        type: string
        description: The negotiated authentication protocol.
        enum:
        - none
        - chap
        - pap
        - both
      username:
        type: string
        description: Username for PAP and/or CHAP.
        minLength: 0
        maxLength: 255
      password:
        type: string
        description: Password for PAP and/or CHAP.
        minLength: 0
        maxLength: 255
    description: The negotiated authentication.
  CellularProfile_pdpContext:
    required:
    - id
    - static
    properties:
      static:
        type: boolean
        description: Use static APN or dynamic.
      id:
        type: integer
        description: Specifies PDP context id.
        minimum: 1
        maximum: 16
      apn:
        type: string
        description: Edit APN of the specified PDP context.
      type:
        type: string
        description: Indicate the PDP type to use.
        enum:
        - ipv4
        - ipv6
        - ipv4v6
      auth:
        $ref: '#/definitions/CellularProfile_pdpContext_auth'
    description: |
      PDP context data for dialing up to Cellular Network.
